# Generated by Django 3.0.7 on 2020-06-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('08.00AM-09.00AM', '08.00AM-09.00AM'), ('09.00AM-10.00AM', '09.00AM-10.00AM'), ('10.00AM-10.00AM', '10.00AM-11.00AM'), ('11.00AM-12.00PM', '11.00AM-12.00PM'), ('12.00PM-01.00PM', '12.00PM-01.00PM'), ('01.00PM-02.00PM', '01.00PM-02.00PM'), ('02.00PM-03.00PM', '02.00PM-03.00PM'), ('03.00PM-04.00PM', '03.00PM-04.00PM'), ('04.00PM-05.00PM', '04.00PM-05.00PM'), ('05.00PM-06.00PM', '05.00PM-06.00PM'), ('06.00PM-07.00PM', '06.00PM-07.00PM'), ('07.00PM-08.00PM', '07.00PM-08.00PM'), ('08.00PM-09.00PM', '08.00PM-09.00PM')], max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('timeSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingApp.TimeSlot')),
            ],
        ),
    ]
